version: '3.8'


services:

  pgdb:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
    - "5431:5432"
    volumes:
    - pgdb:/var/lib/postgresql/data

  django:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate &&
                      python manage.py collectstatic --noinput &&
                      gunicorn orders.wsgi:application --bind 0.0.0.0:8000"
    volumes:
     - .:/usr/src/app
     - static:/usr/src/app/static
    expose:
     - 8000
    depends_on:
     - pgdb

  nginx:
    build: ./nginx
    volumes:
     - static:/usr/src/app/static
     - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - 80:80
    depends_on:
      - django



volumes:
  pgdb:
  static:
