# Generated by Django 5.0.1 on 2024-01-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_productparameter_unique_product_parameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='type',
            field=models.CharField(blank=True, choices=[('shop', 'Магазин'), ('buyer', 'Покупатель')], default='buyer', max_length=20),
        ),
    ]
