# Generated by Django 5.0.1 on 2024-01-27 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_orderitem_unique_order_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='backend.productinfo', verbose_name='Продукт'),
        ),
    ]
