# Generated by Django 5.0.1 on 2024-01-28 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_order_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shop',
        ),
    ]
