# Generated by Django 5.0.1 on 2024-01-28 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_order_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOrderCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='neworder_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
