# Generated by Django 5.0.1 on 2024-01-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_newordercodes_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='assembled',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='NewOrderCodes',
        ),
    ]
