# Generated by Django 5.0.1 on 2024-01-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_orderitem_assembled_delete_newordercodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
